package appfx

import (
	"github.com/nigowl/bitmagnet/internal/adminsettings/adminsettingsfx"
	"github.com/nigowl/bitmagnet/internal/app/cli"
	"github.com/nigowl/bitmagnet/internal/app/cli/args"
	"github.com/nigowl/bitmagnet/internal/app/cli/hooks"
	"github.com/nigowl/bitmagnet/internal/app/cmd/authcmd"
	"github.com/nigowl/bitmagnet/internal/app/cmd/classifiercmd"
	"github.com/nigowl/bitmagnet/internal/app/cmd/configcmd"
	"github.com/nigowl/bitmagnet/internal/app/cmd/processcmd"
	"github.com/nigowl/bitmagnet/internal/app/cmd/reprocesscmd"
	"github.com/nigowl/bitmagnet/internal/app/cmd/workercmd"
	"github.com/nigowl/bitmagnet/internal/auth/authfx"
	"github.com/nigowl/bitmagnet/internal/blocking/blockingfx"
	"github.com/nigowl/bitmagnet/internal/classifier/classifierfx"
	"github.com/nigowl/bitmagnet/internal/config/configfx"
	"github.com/nigowl/bitmagnet/internal/database/databasefx"
	"github.com/nigowl/bitmagnet/internal/database/migrations"
	"github.com/nigowl/bitmagnet/internal/dhtcrawler/dhtcrawlerfx"
	"github.com/nigowl/bitmagnet/internal/gql/gqlfx"
	"github.com/nigowl/bitmagnet/internal/health/healthfx"
	"github.com/nigowl/bitmagnet/internal/httpserver/httpserverfx"
	"github.com/nigowl/bitmagnet/internal/importer/importerfx"
	"github.com/nigowl/bitmagnet/internal/logging/loggingfx"
	"github.com/nigowl/bitmagnet/internal/media/mediafx"
	"github.com/nigowl/bitmagnet/internal/metrics/metricsfx"
	"github.com/nigowl/bitmagnet/internal/processor/processorfx"
	"github.com/nigowl/bitmagnet/internal/protocol/dht/dhtfx"
	"github.com/nigowl/bitmagnet/internal/protocol/metainfo/metainfofx"
	"github.com/nigowl/bitmagnet/internal/queue/queuefx"
	"github.com/nigowl/bitmagnet/internal/telemetry/telemetryfx"
	"github.com/nigowl/bitmagnet/internal/tmdb/tmdbfx"
	"github.com/nigowl/bitmagnet/internal/torznab/torznabfx"
	"github.com/nigowl/bitmagnet/internal/validation/validationfx"
	"github.com/nigowl/bitmagnet/internal/version/versionfx"
	"github.com/nigowl/bitmagnet/internal/webui"
	"github.com/nigowl/bitmagnet/internal/worker/workerfx"
	"go.uber.org/fx"
)

func New() fx.Option {
	return fx.Module(
		"app",
		adminsettingsfx.New(),
		authfx.New(),
		blockingfx.New(),
		classifierfx.New(),
		configfx.New(),
		dhtcrawlerfx.New(),
		dhtfx.New(),
		databasefx.New(),
		gqlfx.New(),
		healthfx.New(),
		httpserverfx.New(),
		importerfx.New(),
		loggingfx.New(),
		mediafx.New(),
		metainfofx.New(),
		metricsfx.New(),
		processorfx.New(),
		queuefx.New(),
		telemetryfx.New(),
		tmdbfx.New(),
		torznabfx.New(),
		validationfx.New(),
		versionfx.New(),
		workerfx.New(),
		fx.Provide(
			args.New,
			cli.New,
			hooks.New,
			// cli commands:
			authcmd.New,
			classifiercmd.New,
			configcmd.New,
			reprocesscmd.New,
			processcmd.New,
			workercmd.New,
		),
		fx.Provide(webui.New),
		fx.Decorate(migrations.NewDecorator),
	)
}
